//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyPACT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyPACT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;data&gt;
        ///  &lt;substance id=&quot;1&quot;&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;-20&lt;/x&gt;
        ///      &lt;y&gt;1582&lt;/y&gt;
        ///    &lt;/point&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;0&lt;/x&gt;
        ///      &lt;y&gt;1547&lt;/y&gt;
        ///    &lt;/point&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;20&lt;/x&gt;
        ///      &lt;y&gt;1513&lt;/y&gt;
        ///    &lt;/point&gt;
        ///  &lt;/substance&gt;
        ///&lt;/data&gt;.
        /// </summary>
        internal static string DensityFromTemperature {
            get {
                return ResourceManager.GetString("DensityFromTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;data&gt;
        ///  &lt;substance id=&quot;1&quot;&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;-20&lt;/x&gt;
        ///      &lt;y&gt;1,49&lt;/y&gt;
        ///    &lt;/point&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;-10&lt;/x&gt;
        ///      &lt;y&gt;1,24&lt;/y&gt;
        ///    &lt;/point&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;0&lt;/x&gt;
        ///      &lt;y&gt;1,05&lt;/y&gt;
        ///    &lt;/point&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;10&lt;/x&gt;
        ///      &lt;y&gt;0,92&lt;/y&gt;
        ///    &lt;/point&gt;
        ///    &lt;point&gt;
        ///      &lt;x&gt;20&lt;/x&gt;
        ///      &lt;y&gt;0,8&lt;/y&gt;
        ///    &lt;/point&gt;
        ///  &lt;/substance&gt;
        ///&lt;/data&gt;.
        /// </summary>
        internal static string ViscosityFromTemperature {
            get {
                return ResourceManager.GetString("ViscosityFromTemperature", resourceCulture);
            }
        }
    }
}
